services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: majdeq/grog_blog-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   image: majdeq/grog_blog-backend:latest
  #   container_name: backend
  #   restart: always
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:16
  #   container_name: postgres
  #   restart: always
  #   env_file:
  #     - ./backend/.env
  #   volumes:
  #     - ./db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
